logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    org.springframework.security: INFO
    com.example.ecom: DEBUG
    org.apache.hc.client5.http: INFO
    
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true